# =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://bluemeet.cqktsjbiytrz.us-east-1.rds.amazonaws.com:3306/bluemeet?serverTimezone=UTC&useSSL=false
    username: admin

# =================================
# = Logging
# =================================
logging:
  level:
    org.springframework: INFO
    org.flywaydb: INFO