# =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://realmeet-db.cqktsjbiytrz.us-east-1.rds.amazonaws.com:3306/realmeet-db&serverTimezone=UTC&useSSL=false
    username: admin